sudo: required
language: go
go: 1.6

install:
  - go get github.com/mu-box/hoarder
  - go get -t -v .
  - hoarder --server -b file:///tmp/hoarder -H "https://127.0.0.1:7410" &
script: go test -v ./...
